name: 160319ARCT
favicon: null
layout_spectrum: 0.02936
typography_spectrum: 0.73574
title: Berlin
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#abd9fd'
    - '#d9f6fe'
    - '#1a1a24'
    - '#656170'
    - '#839ac6'
  brandStrength: 0.0625
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.5
purpose: []
